title: Wildcats Biotech
description: A student-run biotechnology club at the University of Arizona
url: "https://rshaw814.github.io"
baseurl: "/wildcats-biotech"

# Include custom folders
include:
  - _includes
  - assets

# Markdown engine
markdown: kramdown

# Exclude development files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md

sass:
  style: compressed